apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../tunnel
patchesStrategicMerge:
- deployment.yaml
vars:
  - name: DOMAIN
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx-tunnel
    fieldref:
      fieldpath: metadata.annotations.domain
