# $ kustomize build k8s/dev | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../vendor/base
patchesStrategicMerge:
  - vendor/libs/env.yaml
images:
- name: dsyer/template
  newName: gcr.io/cf-sandbox-dsyer/demo