apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: dsyer/demo
    custom:
      buildCommand: cd demo && ./mvnw spring-boot:build-image -D docker.image=$IMAGE && docker push $IMAGE
      dependencies:
        paths:
        - demo/pom.xml
        - demo/src/main/resources
        - demo/target/classes
    sync:
      manual:
      - src: "demo/src/main/resources/**/*"
        dest: /workspace/BOOT-INF/classes
        strip: demo/src/main/resources/
      - src: "demo/target/classes/**/*"
        dest: /workspace/BOOT-INF/classes
        strip: demo/target/classes/
deploy:
  kustomize:
    paths: 
    - "layers/samples/simple"