apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-config-mount
target:
  group: apps
  version: v1
  kind: Deployment
  name: app
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: app
  spec:
    template:
      spec:
        containers:
        - name: app
          env:
            # TODO: This is kind of disappointing:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: prometheus,info,health
