apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-

commonLabels:
  app: demo

resources:
- ../../base
transformers:
- ../../env
- ../../actuator

images:
  - name: dsyer/template
    newName: dsyer/demo
