# $ kustomize build k8s/dev | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - config.yaml
configMapGenerator:
  - name: mysql-config
    behavior: merge
    files:
      - application.properties
vars:
  - name: MYSQL_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
