apiVersion: builtin
kind: PatchTransformer
metadata:
  name: switch-service
target:
  version: v1
  kind: Service
  name: app
patch: |-
  apiVersion: v1
  kind: Service
  metadata:
    name: app
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
