apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo-app
resources:
- ../../base
patchesStrategicMerge:
  - config.yaml
images:
  - name: dsyer/template
    newName: dsyer/demo
configMapGenerator:
  - name: env-config
    behavior: merge
    files:
      - application.yml