apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: demo-
commonLabels:
  app: demo
resources:
- github.com/dsyer/docker-services/layers/base?ref=master
patchesStrategicMerge:
- deployment.yaml
