apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Can replace ../.. with github.com/dsyer/docker-services/layers/
- ../../base
patchesStrategicMerge:
- init.yaml
images:
  - name: dsyer/template
    newName: dsyer/demo
