apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: demo
spec:
  tag: dsyer/demo
  serviceAccount: service-account
  builder:
    name: default-builder
    kind: ClusterBuilder
  source:
    blob:
      url: http://server-app.default.svc.cluster.local:3001/app.jar