# $ kustomize build k8s/dev | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: server-
resources:
- service.yaml
images:
- name: dsyer/template
  newName: dsyer/server