apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- config.yaml
configMapGenerator:
  - name: nginx-config
    behavior: merge
    files:
      - nginx.conf
      - proxy.conf
      - mime.types
