apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    proxy: proxy
spec:
  selector:
    proxy: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    proxy: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      proxy: proxy
  template:
    metadata:
      labels:
        proxy: proxy
    spec:
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
      volumes:
      - name: nginx
        configMap:
          name: nginx-config
