# Creates a server that can be used to store jar files to building images from
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: server-
resources:
- service.yaml
images:
- name: dsyer/template
  newName: dsyer/server