apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Can replace this with github.com/dsyer/docker-services/layers/prometheus
- ../../actuator
- ../../mysql
namePrefix: petclinic-
patchesStrategicMerge:
# Need to build with `--load_restrictor none`
- ../../mysql/app.yaml
- probes.yaml
images:
  - name: dsyer/template
    newName: dsyer/petclinic
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - SPRING_CONFIG_LOCATION=classpath:/,file:///config/mysql/
