apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          # petclinic moves base of actuator endpoints
          livenessProbe:
            httpGet:
              path: /management/info
          readinessProbe:
            httpGet:
              path: /management/health
